url: "https://justgetwet.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/purple" # the subpath of your site, e.g. /blog
title: "In the Purple Rain" # the name of your site, e.g. ACME Corp.
